import { chart } from "../../../src/index.js";

import { createAnnotatedImdbValues } from "./reference-values.js";

export function createAnnotatedImdbPrimitives(rows) {
  const values = createAnnotatedImdbValues(rows);
  const xTicks = values.axes.x.ticks;
  const yTicks = values.axes.y.ticks;
  const bottom = values.bounds.y + values.bounds.height;
  const right = values.bounds.x + values.bounds.width;

  return chart()
    .editSemantic({ property: "dataset[imdb].values", value: values.rows })
    .editSemantic({ property: "layer[point].mark.type", value: "point" })
    .editSemantic({ property: "layer[point].data", value: "imdb" })
    .editSemantic({ property: "layer[point].coordinate", value: "main" })
    .editSemantic({ property: "layer[point].encoding.x.field", value: "Released_Year" })
    .editSemantic({ property: "layer[point].encoding.x.fieldType", value: "temporal" })
    .editSemantic({ property: "layer[point].encoding.x.scale", value: "x" })
    .editSemantic({ property: "layer[point].encoding.y.field", value: "IMDB_Rating" })
    .editSemantic({ property: "layer[point].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[point].encoding.y.scale", value: "y" })
    .editSemantic({ property: "scale[x].type", value: "time" })
    .editSemantic({ property: "scale[x].domain", value: "auto" })
    .editSemantic({ property: "scale[x].range", value: "auto" })
    .editSemantic({ property: "scale[y].type", value: "linear" })
    .editSemantic({ property: "scale[y].domain", value: "auto" })
    .editSemantic({ property: "scale[y].range", value: "auto" })
    .editSemantic({ property: "coordinate[main].type", value: "cartesian" })
    .editSemantic({ property: "guide.axis.x.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.x.scale", value: "x" })
    .editSemantic({ property: "guide.axis.x.title", value: values.axes.x.title })
    .editSemantic({ property: "guide.axis.y.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.y.scale", value: "y" })
    .editSemantic({ property: "guide.axis.y.title", value: values.axes.y.title })
    .editSemantic({ property: "guide.grid.horizontal.coordinate", value: "main" })
    .editSemantic({ property: "guide.grid.horizontal.scale", value: "y" })
    .createGraphics({ id: "canvas", type: "canvas" })
    .editGraphics({ target: "canvas", property: "width", value: values.width })
    .editGraphics({ target: "canvas", property: "height", value: values.height })
    .editGraphics({ target: "canvas", property: "background", value: "white" })
    .createGraphics({ id: "plot-main", parent: "canvas", type: "collection" })
    .createGraphics({
      id: "horizontalGridLines",
      parent: "plot-main",
      type: "line",
      length: yTicks.length
    })
    .editGraphics({ target: "horizontalGridLines", property: "x1", value: values.bounds.x })
    .editGraphics({ target: "horizontalGridLines", property: "y1", value: yTicks.map(tick => tick.position) })
    .editGraphics({ target: "horizontalGridLines", property: "x2", value: right })
    .editGraphics({ target: "horizontalGridLines", property: "y2", value: yTicks.map(tick => tick.position) })
    .editGraphics({ target: "horizontalGridLines", property: "stroke", value: "#e2e8f0" })
    .editGraphics({ target: "horizontalGridLines", property: "strokeWidth", value: 1 })
    .editGraphics({ target: "horizontalGridLines", property: "strokeDash", value: yTicks.map(() => []) })
    .createGraphics({ id: "point", parent: "plot-main", type: "circle", length: values.points.length })
    .editGraphics({ target: "point", property: "x", value: values.points.map(point => point.x) })
    .editGraphics({ target: "point", property: "y", value: values.points.map(point => point.y) })
    .editGraphics({ target: "point", property: "radius", value: values.points.map(point => point.radius) })
    .editGraphics({ target: "point", property: "fill", value: values.points.map(point => point.fill) })
    .createGraphics({ id: "text", parent: "plot-main", type: "text", length: values.labels.length })
    .editGraphics({ target: "text", property: "x", value: values.labels.map(label => label.x) })
    .editGraphics({ target: "text", property: "y", value: values.labels.map(label => label.y) })
    .editGraphics({ target: "text", property: "text", value: values.labels.map(label => label.text) })
    .editGraphics({ target: "text", property: "fill", value: "#334155" })
    .editGraphics({ target: "text", property: "opacity", value: 1 })
    .editGraphics({ target: "text", property: "fontSize", value: 10 })
    .editGraphics({ target: "text", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "text", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "text", property: "textAlign", value: "left" })
    .editGraphics({ target: "text", property: "textBaseline", value: "bottom" })
    .editGraphics({ target: "text", property: "rotation", value: 0 })
    .createGraphics({ id: "xAxisLine", parent: "plot-main", type: "line" })
    .editGraphics({ target: "xAxisLine", property: "x1", value: values.bounds.x })
    .editGraphics({ target: "xAxisLine", property: "y1", value: bottom })
    .editGraphics({ target: "xAxisLine", property: "x2", value: right })
    .editGraphics({ target: "xAxisLine", property: "y2", value: bottom })
    .editGraphics({ target: "xAxisLine", property: "stroke", value: "#334155" })
    .editGraphics({ target: "xAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisTicks", parent: "plot-main", type: "line", length: xTicks.length })
    .editGraphics({ target: "xAxisTicks", property: "x1", value: xTicks.map(tick => tick.position) })
    .editGraphics({ target: "xAxisTicks", property: "y1", value: bottom })
    .editGraphics({ target: "xAxisTicks", property: "x2", value: xTicks.map(tick => tick.position) })
    .editGraphics({ target: "xAxisTicks", property: "y2", value: bottom + 6 })
    .editGraphics({ target: "xAxisTicks", property: "stroke", value: "#64748b" })
    .editGraphics({ target: "xAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisLabels", parent: "plot-main", type: "text", length: xTicks.length })
    .editGraphics({ target: "xAxisLabels", property: "x", value: xTicks.map(tick => tick.position) })
    .editGraphics({ target: "xAxisLabels", property: "y", value: bottom + 18 })
    .editGraphics({ target: "xAxisLabels", property: "text", value: xTicks.map(tick => tick.label) })
    .editGraphics({ target: "xAxisLabels", property: "fill", value: "#334155" })
    .editGraphics({ target: "xAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "xAxisLabels", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "xAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "xAxisLabels", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisLabels", property: "textBaseline", value: "top" })
    .createGraphics({ id: "xAxisTitle", parent: "plot-main", type: "text" })
    .editGraphics({ target: "xAxisTitle", property: "x", value: values.bounds.x + values.bounds.width / 2 })
    .editGraphics({ target: "xAxisTitle", property: "y", value: bottom + 42 })
    .editGraphics({ target: "xAxisTitle", property: "text", value: values.axes.x.title })
    .editGraphics({ target: "xAxisTitle", property: "fill", value: "#334155" })
    .editGraphics({ target: "xAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "xAxisTitle", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "xAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "xAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisTitle", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "xAxisTitle", property: "rotation", value: 0 })
    .createGraphics({ id: "yAxisLine", parent: "plot-main", type: "line" })
    .editGraphics({ target: "yAxisLine", property: "x1", value: values.bounds.x })
    .editGraphics({ target: "yAxisLine", property: "y1", value: bottom })
    .editGraphics({ target: "yAxisLine", property: "x2", value: values.bounds.x })
    .editGraphics({ target: "yAxisLine", property: "y2", value: values.bounds.y })
    .editGraphics({ target: "yAxisLine", property: "stroke", value: "#334155" })
    .editGraphics({ target: "yAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisTicks", parent: "plot-main", type: "line", length: yTicks.length })
    .editGraphics({ target: "yAxisTicks", property: "x1", value: values.bounds.x - 6 })
    .editGraphics({ target: "yAxisTicks", property: "y1", value: yTicks.map(tick => tick.position) })
    .editGraphics({ target: "yAxisTicks", property: "x2", value: values.bounds.x })
    .editGraphics({ target: "yAxisTicks", property: "y2", value: yTicks.map(tick => tick.position) })
    .editGraphics({ target: "yAxisTicks", property: "stroke", value: "#64748b" })
    .editGraphics({ target: "yAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisLabels", parent: "plot-main", type: "text", length: yTicks.length })
    .editGraphics({ target: "yAxisLabels", property: "x", value: values.bounds.x - 12 })
    .editGraphics({ target: "yAxisLabels", property: "y", value: yTicks.map(tick => tick.position) })
    .editGraphics({ target: "yAxisLabels", property: "text", value: yTicks.map(tick => tick.label) })
    .editGraphics({ target: "yAxisLabels", property: "fill", value: "#334155" })
    .editGraphics({ target: "yAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "yAxisLabels", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "yAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "yAxisLabels", property: "textAlign", value: "right" })
    .editGraphics({ target: "yAxisLabels", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "yAxisTitle", parent: "plot-main", type: "text" })
    .editGraphics({ target: "yAxisTitle", property: "x", value: 18 })
    .editGraphics({ target: "yAxisTitle", property: "y", value: values.bounds.y + values.bounds.height / 2 })
    .editGraphics({ target: "yAxisTitle", property: "text", value: values.axes.y.title })
    .editGraphics({ target: "yAxisTitle", property: "fill", value: "#334155" })
    .editGraphics({ target: "yAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "yAxisTitle", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "yAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "yAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "yAxisTitle", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "yAxisTitle", property: "rotation", value: -Math.PI / 2 })
    .createGraphics({ id: "chartTitle", parent: "canvas", type: "text" })
    .editGraphics({ target: "chartTitle", property: "x", value: values.title.x })
    .editGraphics({ target: "chartTitle", property: "y", value: values.title.y })
    .editGraphics({ target: "chartTitle", property: "text", value: values.title.text })
    .editGraphics({ target: "chartTitle", property: "fill", value: "#0f172a" })
    .editGraphics({ target: "chartTitle", property: "fontSize", value: 22 })
    .editGraphics({ target: "chartTitle", property: "fontFamily", value: "sans-serif" })
    .editGraphics({ target: "chartTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "chartTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "chartTitle", property: "textBaseline", value: "middle" });
}
