import type { ChartProgram } from "./program.js";

export type {
  ActionOptions,
  AxisFormat,
  AxisFormatString,
  AxisLabelOptions,
  AxisLabelStyleOptions,
  AxisLineStyleOptions,
  AxisTickOptions,
  AxisTicksAndLabelsOptions,
  AxisTickStyleOptions,
  AxisTitleOptions,
  AxisValue,
  BarWidthOptions,
  CanvasOptions,
  CategoricalEncodingOptions,
  ColorLayout,
  ColorEncodingOptions,
  CompleteAxisOptions,
  ChartProgram,
  ConcretePathCommand,
  CurveInterpolation,
  CreateAxesOptions,
  CreateGridOptions,
  DashPattern,
  DashScaleOptions,
  DashStyle,
  EditGraphicsOptions,
  EditGridOptions,
  EditScaleOptions,
  EditSemanticOptions,
  FieldType,
  GraphicObject,
  GraphicSpec,
  GraphicType,
  GridDirectionOptions,
  HistogramEncodingOptions,
  LegendOptions,
  EditLegendOptions,
  ContinuousColorInterpolation,
  ContinuousColorScaleOptions,
  OpacityEncodingOptions,
  OpacityScaleOptions,
  OffsetScaleOptions,
  PointShape,
  Palette,
  PaletteName,
  PositionEncodingOptions,
  RulePositionEncodingOptions,
  SecondaryPositionEncodingOptions,
  RegressionBandOptions,
  RegressionDataOptions,
  RegressionInterval,
  RegressionMethod,
  RegressionOptions,
  ScaleRange,
  ScaleOptions,
  ScaleType,
  StackMode,
  SemanticSpec,
  StrokeDashEncodingOptions,
  TraceNode,
  TitleOptions,
  EditTitleOptions,
  TitleTextStyleOptions,
  XAxisPosition,
  YAxisPosition,
  XOffsetEncodingOptions
} from "./program.js";

export function chart(): ChartProgram;
export function render(
  program: Pick<ChartProgram, "graphicSpec">,
  context: CanvasRenderingContext2D,
  options?: { pixelRatio?: number }
): void;
