import type { ChartProgram } from "./program.js";

export type {
  ActionOptions,
  AxisFormat,
  AxisFormatString,
  AxisLabelOptions,
  AxisLabelStyleOptions,
  AxisLineStyleOptions,
  AxisTickOptions,
  AxisTicksAndLabelsOptions,
  AxisTickStyleOptions,
  AxisTitleOptions,
  AxisValue,
  BarWidthOptions,
  CanvasOptions,
  CategoricalEncodingOptions,
  ColorLayout,
  ColorEncodingOptions,
  CompleteAxisOptions,
  ChartProgram,
  ConcretePathCommand,
  CurveInterpolation,
  CreateDerivedDataOptions,
  CreateAxesOptions,
  CreateCoordinateOptions,
  CreateGuidesOptions,
  CreateGridOptions,
  CreateRegressionBandOptions,
  CreateRegressionLineOptions,
  CreateScaleOptions,
  DashPattern,
  DashScaleOptions,
  DashStyle,
  DatasetDensityTransform,
  DatasetFilterTransform,
  DatasetIntervalOutputFields,
  DatasetIntervalTransform,
  DatasetRegressionTransform,
  DatasetScalar,
  DatasetTransform,
  EditGraphicsOptions,
  EditAxisOptions,
  EditGridDirectionsOptions,
  EditGridOptions,
  EditErrorBandBoundaryOptions,
  EditErrorBandOptions,
  EditErrorBarOptions,
  EditBoxPlotOptions,
  EditLegendBorderOptions,
  EditLegendLabelsOptions,
  EditLegendLayoutOptions,
  EditLegendSymbolsOptions,
  EditLegendTitleOptions,
  EditScaleOptions,
  EditSemanticOptions,
  FieldType,
  GraphicObject,
  GraphicSpec,
  GraphicType,
  GridDirectionOptions,
  HistogramEncodingOptions,
  HighlightMarksOptions,
  LegendOptions,
  EditLegendOptions,
  ContinuousColorInterpolation,
  ContinuousColorScaleOptions,
  OpacityEncodingOptions,
  OpacityScaleOptions,
  OffsetScaleOptions,
  PointShape,
  MarkSelector,
  MarkGraphicProperty,
  Palette,
  PaletteName,
  PositionEncodingOptions,
  RulePositionEncodingOptions,
  SecondaryPositionEncodingOptions,
  RegressionBandOptions,
  RegressionDataOptions,
  RegressionInterval,
  RegressionMethod,
  RegressionOptions,
  EditRegressionOptions,
  RemoveAxisOptions,
  RemoveGridOptions,
  RemoveLegendOptions,
  RemoveMarkOptions,
  ScaleRange,
  ScaleOptions,
  ScaleType,
  StackMode,
  SemanticCoordinate,
  SemanticDataset,
  SemanticLayer,
  SemanticScale,
  SemanticSpec,
  SelectMarksOptions,
  StrokeDashEncodingOptions,
  TraceNode,
  TitleOptions,
  EditTitleOptions,
  TitleTextStyleOptions,
  XAxisPosition,
  YAxisPosition,
  XOffsetEncodingOptions
} from "./program.js";

export function chart(): ChartProgram;
export function render(
  program: Pick<ChartProgram, "graphicSpec">,
  context: CanvasRenderingContext2D,
  options?: { pixelRatio?: number }
): void;
