import { chart } from "../../../src/index.js";

import {
  GRADIENT_PLOT_FIELDS,
  GRADIENT_PLOT_LAYOUT,
  createCarsGradientPlotReference
} from "./fixture.js";

const AXIS = "#334155";
const GRID = "#e2e8f0";
const MUTED = "#64748b";
const TITLE = "#0f172a";
const FONT = "sans-serif";

export function createCarsGradientPlotPrimitives(cars) {
  const reference = createCarsGradientPlotReference(cars);
  const { bounds, legend } = GRADIENT_PLOT_LAYOUT;
  const profiles = reference.profiles;
  const categoryLabels = profiles.map(profile => profile[GRADIENT_PLOT_FIELDS.category]);
  const centerXs = profiles.map(profile => profile.centerX);
  const tickYs = reference.yTicks.map(tick => tick.y);

  return chart()
    .editSemantic({ property: "dataset[carsAccelerationProfiles].values", value: profiles.map(profile => ({
      [GRADIENT_PLOT_FIELDS.category]: profile[GRADIENT_PLOT_FIELDS.category],
      [GRADIENT_PLOT_FIELDS.values]: profile[GRADIENT_PLOT_FIELDS.values],
      [GRADIENT_PLOT_FIELDS.intensities]: profile[GRADIENT_PLOT_FIELDS.intensities],
      [GRADIENT_PLOT_FIELDS.lower]: profile[GRADIENT_PLOT_FIELDS.lower],
      [GRADIENT_PLOT_FIELDS.upper]: profile[GRADIENT_PLOT_FIELDS.upper],
      [GRADIENT_PLOT_FIELDS.center]: profile[GRADIENT_PLOT_FIELDS.center],
      count: profile.count
    })) })
    .editSemantic({ property: "layer[gradientPlot].mark.type", value: "rect" })
    .editSemantic({ property: "layer[gradientPlot].data", value: "carsAccelerationProfiles" })
    .editSemantic({ property: "layer[gradientPlot].coordinate", value: "main" })
    .editSemantic({ property: "layer[gradientPlot].encoding.x.field", value: GRADIENT_PLOT_FIELDS.category })
    .editSemantic({ property: "layer[gradientPlot].encoding.x.fieldType", value: "nominal" })
    .editSemantic({ property: "layer[gradientPlot].encoding.x.scale", value: "x" })
    .editSemantic({ property: "layer[gradientPlot].encoding.y.field", value: GRADIENT_PLOT_FIELDS.lower })
    .editSemantic({ property: "layer[gradientPlot].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[gradientPlot].encoding.y.scale", value: "y" })
    .editSemantic({ property: "layer[gradientPlot].encoding.y2.field", value: GRADIENT_PLOT_FIELDS.upper })
    .editSemantic({ property: "layer[gradientPlot].encoding.y2.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[gradientPlotCenter].mark.type", value: "rule" })
    .editSemantic({ property: "layer[gradientPlotCenter].data", value: "carsAccelerationProfiles" })
    .editSemantic({ property: "layer[gradientPlotCenter].source", value: "gradientPlot" })
    .editSemantic({ property: "layer[gradientPlotCenter].coordinate", value: "main" })
    .editSemantic({ property: "layer[gradientPlotCenter].encoding.x.field", value: GRADIENT_PLOT_FIELDS.category })
    .editSemantic({ property: "layer[gradientPlotCenter].encoding.x.fieldType", value: "nominal" })
    .editSemantic({ property: "layer[gradientPlotCenter].encoding.x.scale", value: "x" })
    .editSemantic({ property: "layer[gradientPlotCenter].encoding.y.field", value: GRADIENT_PLOT_FIELDS.center })
    .editSemantic({ property: "layer[gradientPlotCenter].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[gradientPlotCenter].encoding.y.scale", value: "y" })
    .editSemantic({ property: "scale[x].type", value: "band" })
    .editSemantic({ property: "scale[x].domain", value: reference.categories })
    .editSemantic({ property: "scale[x].range", value: [bounds.left, bounds.right] })
    .editSemantic({ property: "scale[y].type", value: "linear" })
    .editSemantic({ property: "scale[y].domain", value: reference.extent })
    .editSemantic({ property: "scale[y].range", value: [bounds.bottom, bounds.top] })
    .editSemantic({ property: "scale[color].type", value: "sequential" })
    .editSemantic({ property: "scale[color].domain", value: [0, reference.maximumIntensity] })
    .editSemantic({ property: "scale[color].range", value: { palette: { name: "blues" } } })
    .editSemantic({ property: "coordinate[main].type", value: "cartesian" })
    .editSemantic({ property: "guide.axis.x.scale", value: "x" })
    .editSemantic({ property: "guide.axis.x.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.x.title", value: "Origin" })
    .editSemantic({ property: "guide.axis.y.scale", value: "y" })
    .editSemantic({ property: "guide.axis.y.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.y.title", value: "Acceleration" })
    .editSemantic({ property: "guide.legend.color.scale", value: "color" })
    .editSemantic({ property: "guide.legend.color.title", value: "Relative density" })
    .editSemantic({ property: "title.text", value: "Acceleration Distribution by Origin" })
    .editSemantic({ property: "title.subtitle", value: "Gradient intensity shows the within-origin density" })
    .createGraphics({ id: "canvas", type: "canvas" })
    .editGraphics({ target: "canvas", property: "width", value: GRADIENT_PLOT_LAYOUT.width })
    .editGraphics({ target: "canvas", property: "height", value: GRADIENT_PLOT_LAYOUT.height })
    .editGraphics({ target: "canvas", property: "background", value: "white" })
    .createGraphics({ id: "plot", type: "collection", parent: "canvas" })
    .createGraphics({ id: "grid", type: "line", length: reference.yTicks.length, parent: "plot" })
    .editGraphics({ target: "grid", property: "x1", value: bounds.left })
    .editGraphics({ target: "grid", property: "y1", value: tickYs })
    .editGraphics({ target: "grid", property: "x2", value: bounds.right })
    .editGraphics({ target: "grid", property: "y2", value: tickYs })
    .editGraphics({ target: "grid", property: "stroke", value: GRID })
    .editGraphics({ target: "grid", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "gradientPlot", type: "rect", length: profiles.length, parent: "plot" })
    .editGraphics({ target: "gradientPlot", property: "x", value: profiles.map(profile => profile.x) })
    .editGraphics({ target: "gradientPlot", property: "y", value: profiles.map(profile => profile.y) })
    .editGraphics({ target: "gradientPlot", property: "width", value: profiles.map(profile => profile.width) })
    .editGraphics({ target: "gradientPlot", property: "height", value: profiles.map(profile => profile.height) })
    .editGraphics({ target: "gradientPlot", property: "fill", value: profiles.map(profile => profile.fill) })
    .editGraphics({ target: "gradientPlot", property: "stroke", value: "#cbd5e1" })
    .editGraphics({ target: "gradientPlot", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "gradientPlotCenter", type: "line", length: profiles.length, parent: "plot" })
    .editGraphics({ target: "gradientPlotCenter", property: "x1", value: profiles.map(profile => profile.x + 8) })
    .editGraphics({ target: "gradientPlotCenter", property: "y1", value: profiles.map(profile => profile.centerY) })
    .editGraphics({ target: "gradientPlotCenter", property: "x2", value: profiles.map(profile => profile.x + profile.width - 8) })
    .editGraphics({ target: "gradientPlotCenter", property: "y2", value: profiles.map(profile => profile.centerY) })
    .editGraphics({ target: "gradientPlotCenter", property: "stroke", value: TITLE })
    .editGraphics({ target: "gradientPlotCenter", property: "strokeWidth", value: 1.5 })
    .createGraphics({ id: "xAxisLine", type: "line", parent: "plot" })
    .editGraphics({ target: "xAxisLine", property: "x1", value: bounds.left })
    .editGraphics({ target: "xAxisLine", property: "y1", value: bounds.bottom })
    .editGraphics({ target: "xAxisLine", property: "x2", value: bounds.right })
    .editGraphics({ target: "xAxisLine", property: "y2", value: bounds.bottom })
    .editGraphics({ target: "xAxisLine", property: "stroke", value: AXIS })
    .editGraphics({ target: "xAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisLine", type: "line", parent: "plot" })
    .editGraphics({ target: "yAxisLine", property: "x1", value: bounds.left })
    .editGraphics({ target: "yAxisLine", property: "y1", value: bounds.top })
    .editGraphics({ target: "yAxisLine", property: "x2", value: bounds.left })
    .editGraphics({ target: "yAxisLine", property: "y2", value: bounds.bottom })
    .editGraphics({ target: "yAxisLine", property: "stroke", value: AXIS })
    .editGraphics({ target: "yAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisLabels", type: "text", length: profiles.length, parent: "plot" })
    .editGraphics({ target: "xAxisLabels", property: "x", value: centerXs })
    .editGraphics({ target: "xAxisLabels", property: "y", value: bounds.bottom + 18 })
    .editGraphics({ target: "xAxisLabels", property: "text", value: categoryLabels })
    .editGraphics({ target: "xAxisLabels", property: "fill", value: AXIS })
    .editGraphics({ target: "xAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "xAxisLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "xAxisLabels", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisLabels", property: "textBaseline", value: "top" })
    .createGraphics({ id: "yAxisLabels", type: "text", length: reference.yTicks.length, parent: "plot" })
    .editGraphics({ target: "yAxisLabels", property: "x", value: bounds.left - 12 })
    .editGraphics({ target: "yAxisLabels", property: "y", value: tickYs })
    .editGraphics({ target: "yAxisLabels", property: "text", value: reference.yTicks.map(tick => tick.label) })
    .editGraphics({ target: "yAxisLabels", property: "fill", value: MUTED })
    .editGraphics({ target: "yAxisLabels", property: "fontSize", value: 11 })
    .editGraphics({ target: "yAxisLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "yAxisLabels", property: "textAlign", value: "right" })
    .editGraphics({ target: "yAxisLabels", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "xAxisTitle", type: "text", parent: "plot" })
    .editGraphics({ target: "xAxisTitle", property: "x", value: (bounds.left + bounds.right) / 2 })
    .editGraphics({ target: "xAxisTitle", property: "y", value: bounds.bottom + 52 })
    .editGraphics({ target: "xAxisTitle", property: "text", value: "Origin" })
    .editGraphics({ target: "xAxisTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "xAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "xAxisTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "xAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "xAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "yAxisTitle", type: "text", parent: "plot" })
    .editGraphics({ target: "yAxisTitle", property: "x", value: bounds.left - 52 })
    .editGraphics({ target: "yAxisTitle", property: "y", value: (bounds.top + bounds.bottom) / 2 })
    .editGraphics({ target: "yAxisTitle", property: "text", value: "Acceleration" })
    .editGraphics({ target: "yAxisTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "yAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "yAxisTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "yAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "yAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "yAxisTitle", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "yAxisTitle", property: "rotation", value: -Math.PI / 2 })
    .createGraphics({ id: "densityLegend", type: "rect", parent: "canvas" })
    .editGraphics({ target: "densityLegend", property: "x", value: legend.x })
    .editGraphics({ target: "densityLegend", property: "y", value: legend.y })
    .editGraphics({ target: "densityLegend", property: "width", value: legend.width })
    .editGraphics({ target: "densityLegend", property: "height", value: legend.height })
    .editGraphics({ target: "densityLegend", property: "fill", value: reference.legendPaint })
    .editGraphics({ target: "densityLegend", property: "stroke", value: "#cbd5e1" })
    .editGraphics({ target: "densityLegend", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "densityLegendLabels", type: "text", length: 2, parent: "canvas" })
    .editGraphics({ target: "densityLegendLabels", property: "x", value: legend.x + legend.width + 10 })
    .editGraphics({ target: "densityLegendLabels", property: "y", value: [legend.y + legend.height, legend.y] })
    .editGraphics({ target: "densityLegendLabels", property: "text", value: ["Low", "High"] })
    .editGraphics({ target: "densityLegendLabels", property: "fill", value: MUTED })
    .editGraphics({ target: "densityLegendLabels", property: "fontSize", value: 11 })
    .editGraphics({ target: "densityLegendLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "densityLegendLabels", property: "textAlign", value: "left" })
    .editGraphics({ target: "densityLegendLabels", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "densityLegendTitle", type: "text", parent: "canvas" })
    .editGraphics({ target: "densityLegendTitle", property: "x", value: legend.x })
    .editGraphics({ target: "densityLegendTitle", property: "y", value: legend.y - 18 })
    .editGraphics({ target: "densityLegendTitle", property: "text", value: "Relative density" })
    .editGraphics({ target: "densityLegendTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "densityLegendTitle", property: "fontSize", value: 12 })
    .editGraphics({ target: "densityLegendTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "densityLegendTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "densityLegendTitle", property: "textAlign", value: "left" })
    .editGraphics({ target: "densityLegendTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "chartTitle", type: "text", parent: "canvas" })
    .editGraphics({ target: "chartTitle", property: "x", value: (bounds.left + bounds.right) / 2 })
    .editGraphics({ target: "chartTitle", property: "y", value: 30 })
    .editGraphics({ target: "chartTitle", property: "text", value: "Acceleration Distribution by Origin" })
    .editGraphics({ target: "chartTitle", property: "fill", value: TITLE })
    .editGraphics({ target: "chartTitle", property: "fontSize", value: 21 })
    .editGraphics({ target: "chartTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "chartTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "chartTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "chartTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "chartSubtitle", type: "text", parent: "canvas" })
    .editGraphics({ target: "chartSubtitle", property: "x", value: (bounds.left + bounds.right) / 2 })
    .editGraphics({ target: "chartSubtitle", property: "y", value: 55 })
    .editGraphics({ target: "chartSubtitle", property: "text", value: "Gradient intensity shows the within-origin density" })
    .editGraphics({ target: "chartSubtitle", property: "fill", value: MUTED })
    .editGraphics({ target: "chartSubtitle", property: "fontSize", value: 12 })
    .editGraphics({ target: "chartSubtitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "chartSubtitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "chartSubtitle", property: "textBaseline", value: "middle" });
}
