import { chart } from "../../../src/index.js";

import {
  BAND_POINT_LAYOUT,
  TIME_LAYOUT,
  createBandPointReference,
  createTimeReference
} from "./reference-values.js";

const FONT = "sans-serif";
const AXIS = "#334155";
const MUTED = "#64748b";
const GRID = "#e2e8f0";

export function createGapminderBandPointPrimitives(gapminder) {
  const values = createBandPointReference(gapminder);
  const { width, height } = BAND_POINT_LAYOUT;
  const { rows2005, rows, plot, domain, band, point, centers, yDomain, yTicks, yPositions, bars } = values;
  const labels = domain;
  const yLabels = yTicks.map(value => value === 0 ? "0" : `${value / 1_000_000}M`);

  let program = chart()
    .editSemantic({ property: "dataset[data].values", value: gapminder })
    .editSemantic({ property: "dataset[gapminder2005].source", value: "data" })
    .editSemantic({ property: "dataset[gapminder2005].transform", value: [{ type: "filter", field: "year", predicate: { op: "eq", value: 2005 } }] })
    .editSemantic({ property: "dataset[gapminder2005].values", value: rows2005 })
    .editSemantic({ property: "dataset[selectedCountries].source", value: "gapminder2005" })
    .editSemantic({ property: "dataset[selectedCountries].transform", value: [{ type: "filter", field: "country", oneOf: domain }] })
    .editSemantic({ property: "dataset[selectedCountries].values", value: rows })
    .editSemantic({ property: "layer[bar].mark.type", value: "bar" })
    .editSemantic({ property: "layer[bar].data", value: "selectedCountries" })
    .editSemantic({ property: "layer[bar].coordinate", value: "main" })
    .editSemantic({ property: "layer[bar].encoding.x.field", value: "country" })
    .editSemantic({ property: "layer[bar].encoding.x.fieldType", value: "nominal" })
    .editSemantic({ property: "layer[bar].encoding.x.scale", value: "x" })
    .editSemantic({ property: "layer[bar].encoding.y.field", value: "pop" })
    .editSemantic({ property: "layer[bar].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[bar].encoding.y.aggregate", value: "mean" })
    .editSemantic({ property: "layer[bar].encoding.y.scale", value: "y" })
    .editSemantic({ property: "layer[point].mark.type", value: "point" })
    .editSemantic({ property: "layer[point].data", value: "selectedCountries" })
    .editSemantic({ property: "layer[point].coordinate", value: "main" })
    .editSemantic({ property: "layer[point].encoding.x.field", value: "country" })
    .editSemantic({ property: "layer[point].encoding.x.fieldType", value: "nominal" })
    .editSemantic({ property: "layer[point].encoding.x.scale", value: "countryPoint" })
    .editSemantic({ property: "layer[point].encoding.y.field", value: "pop" })
    .editSemantic({ property: "layer[point].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[point].encoding.y.scale", value: "y" })
    .editSemantic({ property: "scale[x].type", value: "band" })
    .editSemantic({ property: "scale[x].domain", value: "auto" })
    .editSemantic({ property: "scale[x].range", value: "auto" })
    .editSemantic({ property: "scale[x].paddingInner", value: band.paddingInner })
    .editSemantic({ property: "scale[x].paddingOuter", value: band.paddingOuter })
    .editSemantic({ property: "scale[x].align", value: 0.5 })
    .editSemantic({ property: "scale[countryPoint].type", value: "point" })
    .editSemantic({ property: "scale[countryPoint].domain", value: "auto" })
    .editSemantic({ property: "scale[countryPoint].range", value: "auto" })
    .editSemantic({ property: "scale[countryPoint].padding", value: point.padding })
    .editSemantic({ property: "scale[countryPoint].align", value: 0.5 })
    .editSemantic({ property: "scale[y].type", value: "linear" })
    .editSemantic({ property: "scale[y].domain", value: "auto" })
    .editSemantic({ property: "scale[y].range", value: "auto" })
    .editSemantic({ property: "scale[y].nice", value: true })
    .editSemantic({ property: "scale[y].zero", value: true })
    .editSemantic({ property: "coordinate[main].type", value: "cartesian" })
    .editSemantic({ property: "guide.axis.x.scale", value: "x" })
    .editSemantic({ property: "guide.axis.x.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.x.title", value: "Country" })
    .editSemantic({ property: "guide.axis.y.scale", value: "y" })
    .editSemantic({ property: "guide.axis.y.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.y.title", value: "Population" })
    .editSemantic({ property: "guide.grid.horizontal.scale", value: "y" })
    .editSemantic({ property: "guide.grid.horizontal.coordinate", value: "main" })
    .editSemantic({ property: "title.text", value: "Population by Country" })
    .editSemantic({ property: "title.subtitle", value: "Band slots with aligned point centers · 2005" })
    .createGraphics({ id: "canvas", type: "canvas" })
    .editGraphics({ target: "canvas", property: "width", value: width })
    .editGraphics({ target: "canvas", property: "height", value: height })
    .editGraphics({ target: "canvas", property: "background", value: "white" })
    .createGraphics({ id: "horizontalGridLines", type: "line", length: yTicks.length })
    .editGraphics({ target: "horizontalGridLines", property: "x1", value: plot.left })
    .editGraphics({ target: "horizontalGridLines", property: "y1", value: yPositions })
    .editGraphics({ target: "horizontalGridLines", property: "x2", value: plot.right })
    .editGraphics({ target: "horizontalGridLines", property: "y2", value: yPositions })
    .editGraphics({ target: "horizontalGridLines", property: "stroke", value: GRID })
    .editGraphics({ target: "horizontalGridLines", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "bar", type: "rect", length: bars.length })
    .editGraphics({ target: "bar", property: "x", value: bars.map(bar => bar.x) })
    .editGraphics({ target: "bar", property: "y", value: bars.map(bar => bar.y) })
    .editGraphics({ target: "bar", property: "width", value: bars.map(bar => bar.width) })
    .editGraphics({ target: "bar", property: "height", value: bars.map(bar => bar.height) })
    .editGraphics({ target: "bar", property: "fill", value: "#cbd5e1" })
    .editGraphics({ target: "bar", property: "stroke", value: "white" })
    .editGraphics({ target: "bar", property: "strokeWidth", value: 0.5 })
    .editGraphics({ target: "bar", property: "opacity", value: 1 })
    .createGraphics({ id: "point", type: "circle", length: rows.length })
    .editGraphics({ target: "point", property: "x", value: centers })
    .editGraphics({ target: "point", property: "y", value: bars.map(bar => bar.y) })
    .editGraphics({ target: "point", property: "radius", value: 5 })
    .editGraphics({ target: "point", property: "fill", value: "#2563eb" })
    .editGraphics({ target: "point", property: "stroke", value: "white" })
    .editGraphics({ target: "point", property: "strokeWidth", value: 1 });

  const line = { stroke: AXIS, strokeWidth: 1 };
  program = program
    .createGraphics({ id: "xAxisLine", type: "line" })
    .editGraphics({ target: "xAxisLine", property: "x1", value: plot.left })
    .editGraphics({ target: "xAxisLine", property: "y1", value: plot.bottom })
    .editGraphics({ target: "xAxisLine", property: "x2", value: plot.right })
    .editGraphics({ target: "xAxisLine", property: "y2", value: plot.bottom })
    .editGraphics({ target: "xAxisLine", property: "stroke", value: line.stroke })
    .editGraphics({ target: "xAxisLine", property: "strokeWidth", value: line.strokeWidth })
    .createGraphics({ id: "yAxisLine", type: "line" })
    .editGraphics({ target: "yAxisLine", property: "x1", value: plot.left })
    .editGraphics({ target: "yAxisLine", property: "y1", value: plot.bottom })
    .editGraphics({ target: "yAxisLine", property: "x2", value: plot.left })
    .editGraphics({ target: "yAxisLine", property: "y2", value: plot.top })
    .editGraphics({ target: "yAxisLine", property: "stroke", value: line.stroke })
    .editGraphics({ target: "yAxisLine", property: "strokeWidth", value: line.strokeWidth })
    .createGraphics({ id: "xAxisTicks", type: "line", length: centers.length })
    .editGraphics({ target: "xAxisTicks", property: "x1", value: centers })
    .editGraphics({ target: "xAxisTicks", property: "y1", value: plot.bottom })
    .editGraphics({ target: "xAxisTicks", property: "x2", value: centers })
    .editGraphics({ target: "xAxisTicks", property: "y2", value: plot.bottom + 5 })
    .editGraphics({ target: "xAxisTicks", property: "stroke", value: MUTED })
    .editGraphics({ target: "xAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisTicks", type: "line", length: yTicks.length })
    .editGraphics({ target: "yAxisTicks", property: "x1", value: plot.left - 5 })
    .editGraphics({ target: "yAxisTicks", property: "y1", value: yPositions })
    .editGraphics({ target: "yAxisTicks", property: "x2", value: plot.left })
    .editGraphics({ target: "yAxisTicks", property: "y2", value: yPositions })
    .editGraphics({ target: "yAxisTicks", property: "stroke", value: MUTED })
    .editGraphics({ target: "yAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisLabels", type: "text", length: labels.length })
    .editGraphics({ target: "xAxisLabels", property: "x", value: centers })
    .editGraphics({ target: "xAxisLabels", property: "y", value: plot.bottom + 12 })
    .editGraphics({ target: "xAxisLabels", property: "text", value: labels })
    .createGraphics({ id: "yAxisLabels", type: "text", length: yLabels.length })
    .editGraphics({ target: "yAxisLabels", property: "x", value: plot.left - 10 })
    .editGraphics({ target: "yAxisLabels", property: "y", value: yPositions })
    .editGraphics({ target: "yAxisLabels", property: "text", value: yLabels })
    .editGraphics({ target: "xAxisLabels", property: "fill", value: AXIS })
    .editGraphics({ target: "xAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "xAxisLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "xAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "xAxisLabels", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisLabels", property: "textBaseline", value: "top" })
    .editGraphics({ target: "yAxisLabels", property: "fill", value: AXIS })
    .editGraphics({ target: "yAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "yAxisLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "yAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "yAxisLabels", property: "textAlign", value: "right" })
    .editGraphics({ target: "yAxisLabels", property: "textBaseline", value: "middle" });

  return program
    .createGraphics({ id: "xAxisTitle", type: "text" })
    .editGraphics({ target: "xAxisTitle", property: "x", value: (plot.left + plot.right) / 2 })
    .editGraphics({ target: "xAxisTitle", property: "y", value: 296 })
    .editGraphics({ target: "xAxisTitle", property: "text", value: "Country" })
    .editGraphics({ target: "xAxisTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "xAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "xAxisTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "xAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "xAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "yAxisTitle", type: "text" })
    .editGraphics({ target: "yAxisTitle", property: "x", value: 16 })
    .editGraphics({ target: "yAxisTitle", property: "y", value: (plot.top + plot.bottom) / 2 })
    .editGraphics({ target: "yAxisTitle", property: "text", value: "Population" })
    .editGraphics({ target: "yAxisTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "yAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "yAxisTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "yAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "yAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "yAxisTitle", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "yAxisTitle", property: "rotation", value: -Math.PI / 2 })
    .createGraphics({ id: "chartTitle", type: "text" })
    .editGraphics({ target: "chartTitle", property: "x", value: plot.left })
    .editGraphics({ target: "chartTitle", property: "y", value: 18 })
    .editGraphics({ target: "chartTitle", property: "text", value: "Population by Country" })
    .editGraphics({ target: "chartTitle", property: "fill", value: "#0f172a" })
    .editGraphics({ target: "chartTitle", property: "fontSize", value: 18 })
    .editGraphics({ target: "chartTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "chartTitle", property: "fontWeight", value: 700 })
    .editGraphics({ target: "chartTitle", property: "textAlign", value: "left" })
    .editGraphics({ target: "chartTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "chartSubtitle", type: "text" })
    .editGraphics({ target: "chartSubtitle", property: "x", value: plot.left })
    .editGraphics({ target: "chartSubtitle", property: "y", value: 40 })
    .editGraphics({ target: "chartSubtitle", property: "text", value: "Band slots with aligned point centers · 2005" })
    .editGraphics({ target: "chartSubtitle", property: "fill", value: MUTED })
    .editGraphics({ target: "chartSubtitle", property: "fontSize", value: 12 })
    .editGraphics({ target: "chartSubtitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "chartSubtitle", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "chartSubtitle", property: "textAlign", value: "left" })
    .editGraphics({ target: "chartSubtitle", property: "textBaseline", value: "middle" });
}

export function createGapminderTimePrimitives(gapminder) {
  const values = createTimeReference(gapminder);
  const { width, height } = TIME_LAYOUT;
  const { rows, plot, countries, colors, xDomain, xTickYears, xPositions, yDomain, yTicks, yPositions, series } = values;

  let program = chart()
    .editSemantic({ property: "dataset[data].values", value: gapminder })
    .editSemantic({ property: "dataset[selectedCountries].source", value: "data" })
    .editSemantic({ property: "dataset[selectedCountries].transform", value: [{ type: "filter", field: "country", oneOf: countries }] })
    .editSemantic({ property: "dataset[selectedCountries].values", value: rows })
    .editSemantic({ property: "layer[line].mark.type", value: "line" })
    .editSemantic({ property: "layer[line].data", value: "selectedCountries" })
    .editSemantic({ property: "layer[line].coordinate", value: "main" })
    .editSemantic({ property: "layer[line].encoding.x.field", value: "year" })
    .editSemantic({ property: "layer[line].encoding.x.fieldType", value: "temporal" })
    .editSemantic({ property: "layer[line].encoding.x.scale", value: "x" })
    .editSemantic({ property: "layer[line].encoding.y.field", value: "life_expect" })
    .editSemantic({ property: "layer[line].encoding.y.fieldType", value: "quantitative" })
    .editSemantic({ property: "layer[line].encoding.y.aggregate", value: "mean" })
    .editSemantic({ property: "layer[line].encoding.y.scale", value: "y" })
    .editSemantic({ property: "layer[line].encoding.color.field", value: "country" })
    .editSemantic({ property: "layer[line].encoding.color.fieldType", value: "nominal" })
    .editSemantic({ property: "layer[line].encoding.color.scale", value: "color" })
    .editSemantic({ property: "scale[x].type", value: "time" })
    .editSemantic({ property: "scale[x].domain", value: "auto" })
    .editSemantic({ property: "scale[x].range", value: "auto" })
    .editSemantic({ property: "scale[x].nice", value: true })
    .editSemantic({ property: "scale[y].type", value: "linear" })
    .editSemantic({ property: "scale[y].domain", value: "auto" })
    .editSemantic({ property: "scale[y].range", value: "auto" })
    .editSemantic({ property: "scale[y].nice", value: true })
    .editSemantic({ property: "scale[y].zero", value: false })
    .editSemantic({ property: "scale[color].type", value: "ordinal" })
    .editSemantic({ property: "scale[color].domain", value: "auto" })
    .editSemantic({ property: "scale[color].range", value: { palette: { name: "tableau10" } } })
    .editSemantic({ property: "coordinate[main].type", value: "cartesian" })
    .editSemantic({ property: "guide.axis.x.scale", value: "x" })
    .editSemantic({ property: "guide.axis.x.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.x.title", value: "Year" })
    .editSemantic({ property: "guide.axis.y.scale", value: "y" })
    .editSemantic({ property: "guide.axis.y.coordinate", value: "main" })
    .editSemantic({ property: "guide.axis.y.title", value: "Life expectancy" })
    .editSemantic({ property: "guide.grid.horizontal.scale", value: "y" })
    .editSemantic({ property: "guide.grid.horizontal.coordinate", value: "main" })
    .editSemantic({ property: "guide.legend.color.scale", value: "color" })
    .editSemantic({ property: "guide.legend.color.title", value: "Country" })
    .editSemantic({ property: "title.text", value: "Life Expectancy over Time" })
    .editSemantic({ property: "title.subtitle", value: "UTC year positions · 1955–2005" })
    .createGraphics({ id: "canvas", type: "canvas" })
    .editGraphics({ target: "canvas", property: "width", value: width })
    .editGraphics({ target: "canvas", property: "height", value: height })
    .editGraphics({ target: "canvas", property: "background", value: "white" })
    .createGraphics({ id: "horizontalGridLines", type: "line", length: yTicks.length })
    .editGraphics({ target: "horizontalGridLines", property: "x1", value: plot.left })
    .editGraphics({ target: "horizontalGridLines", property: "y1", value: yPositions })
    .editGraphics({ target: "horizontalGridLines", property: "x2", value: plot.right })
    .editGraphics({ target: "horizontalGridLines", property: "y2", value: yPositions })
    .editGraphics({ target: "horizontalGridLines", property: "stroke", value: GRID })
    .editGraphics({ target: "horizontalGridLines", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "line", type: "path", length: series.length })
    .editGraphics({ target: "line", property: "commands", value: series.map(item => item.commands) })
    .editGraphics({ target: "line", property: "stroke", value: series.map(item => item.color) })
    .editGraphics({ target: "line", property: "strokeWidth", value: 3 });

  const xLabels = xTickYears.map(String);
  const yLabels = yTicks.map(String);
  program = program
    .createGraphics({ id: "xAxisLine", type: "line" })
    .editGraphics({ target: "xAxisLine", property: "x1", value: plot.left })
    .editGraphics({ target: "xAxisLine", property: "y1", value: plot.bottom })
    .editGraphics({ target: "xAxisLine", property: "x2", value: plot.right })
    .editGraphics({ target: "xAxisLine", property: "y2", value: plot.bottom })
    .editGraphics({ target: "xAxisLine", property: "stroke", value: AXIS })
    .editGraphics({ target: "xAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisLine", type: "line" })
    .editGraphics({ target: "yAxisLine", property: "x1", value: plot.left })
    .editGraphics({ target: "yAxisLine", property: "y1", value: plot.bottom })
    .editGraphics({ target: "yAxisLine", property: "x2", value: plot.left })
    .editGraphics({ target: "yAxisLine", property: "y2", value: plot.top })
    .editGraphics({ target: "yAxisLine", property: "stroke", value: AXIS })
    .editGraphics({ target: "yAxisLine", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisTicks", type: "line", length: xPositions.length })
    .editGraphics({ target: "xAxisTicks", property: "x1", value: xPositions })
    .editGraphics({ target: "xAxisTicks", property: "y1", value: plot.bottom })
    .editGraphics({ target: "xAxisTicks", property: "x2", value: xPositions })
    .editGraphics({ target: "xAxisTicks", property: "y2", value: plot.bottom + 5 })
    .editGraphics({ target: "xAxisTicks", property: "stroke", value: MUTED })
    .editGraphics({ target: "xAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "yAxisTicks", type: "line", length: yPositions.length })
    .editGraphics({ target: "yAxisTicks", property: "x1", value: plot.left - 5 })
    .editGraphics({ target: "yAxisTicks", property: "y1", value: yPositions })
    .editGraphics({ target: "yAxisTicks", property: "x2", value: plot.left })
    .editGraphics({ target: "yAxisTicks", property: "y2", value: yPositions })
    .editGraphics({ target: "yAxisTicks", property: "stroke", value: MUTED })
    .editGraphics({ target: "yAxisTicks", property: "strokeWidth", value: 1 })
    .createGraphics({ id: "xAxisLabels", type: "text", length: xLabels.length })
    .editGraphics({ target: "xAxisLabels", property: "x", value: xPositions })
    .editGraphics({ target: "xAxisLabels", property: "y", value: plot.bottom + 12 })
    .editGraphics({ target: "xAxisLabels", property: "text", value: xLabels })
    .createGraphics({ id: "yAxisLabels", type: "text", length: yLabels.length })
    .editGraphics({ target: "yAxisLabels", property: "x", value: plot.left - 10 })
    .editGraphics({ target: "yAxisLabels", property: "y", value: yPositions })
    .editGraphics({ target: "yAxisLabels", property: "text", value: yLabels })
    .editGraphics({ target: "xAxisLabels", property: "fill", value: AXIS })
    .editGraphics({ target: "xAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "xAxisLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "xAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "xAxisLabels", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisLabels", property: "textBaseline", value: "top" })
    .editGraphics({ target: "yAxisLabels", property: "fill", value: AXIS })
    .editGraphics({ target: "yAxisLabels", property: "fontSize", value: 12 })
    .editGraphics({ target: "yAxisLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "yAxisLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "yAxisLabels", property: "textAlign", value: "right" })
    .editGraphics({ target: "yAxisLabels", property: "textBaseline", value: "middle" });

  program = program
    .createGraphics({ id: "legendSymbols", type: "line", length: countries.length })
    .editGraphics({ target: "legendSymbols", property: "x1", value: 338 })
    .editGraphics({ target: "legendSymbols", property: "x2", value: 354 })
    .editGraphics({ target: "legendSymbols", property: "y1", value: [100, 130, 160] })
    .editGraphics({ target: "legendSymbols", property: "y2", value: [100, 130, 160] })
    .editGraphics({ target: "legendSymbols", property: "stroke", value: colors })
    .editGraphics({ target: "legendSymbols", property: "strokeWidth", value: 3 })
    .createGraphics({ id: "legendLabels", type: "text", length: countries.length })
    .editGraphics({ target: "legendLabels", property: "x", value: 362 })
    .editGraphics({ target: "legendLabels", property: "y", value: [100, 130, 160] })
    .editGraphics({ target: "legendLabels", property: "text", value: countries })
    .createGraphics({ id: "legendTitle", type: "text" })
    .editGraphics({ target: "legendTitle", property: "x", value: 338 })
    .editGraphics({ target: "legendTitle", property: "y", value: 76 })
    .editGraphics({ target: "legendTitle", property: "text", value: "Country" })
    .editGraphics({ target: "legendLabels", property: "fill", value: AXIS })
    .editGraphics({ target: "legendLabels", property: "fontSize", value: 11 })
    .editGraphics({ target: "legendLabels", property: "fontFamily", value: FONT })
    .editGraphics({ target: "legendLabels", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "legendLabels", property: "textAlign", value: "left" })
    .editGraphics({ target: "legendLabels", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "legendTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "legendTitle", property: "fontSize", value: 12 })
    .editGraphics({ target: "legendTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "legendTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "legendTitle", property: "textAlign", value: "left" })
    .editGraphics({ target: "legendTitle", property: "textBaseline", value: "middle" });

  return program
    .createGraphics({ id: "xAxisTitle", type: "text" })
    .editGraphics({ target: "xAxisTitle", property: "x", value: (plot.left + plot.right) / 2 })
    .editGraphics({ target: "xAxisTitle", property: "y", value: 296 })
    .editGraphics({ target: "xAxisTitle", property: "text", value: "Year" })
    .editGraphics({ target: "xAxisTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "xAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "xAxisTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "xAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "xAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "xAxisTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "yAxisTitle", type: "text" })
    .editGraphics({ target: "yAxisTitle", property: "x", value: 16 })
    .editGraphics({ target: "yAxisTitle", property: "y", value: (plot.top + plot.bottom) / 2 })
    .editGraphics({ target: "yAxisTitle", property: "text", value: "Life expectancy" })
    .editGraphics({ target: "yAxisTitle", property: "fill", value: AXIS })
    .editGraphics({ target: "yAxisTitle", property: "fontSize", value: 13 })
    .editGraphics({ target: "yAxisTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "yAxisTitle", property: "fontWeight", value: 600 })
    .editGraphics({ target: "yAxisTitle", property: "textAlign", value: "center" })
    .editGraphics({ target: "yAxisTitle", property: "textBaseline", value: "middle" })
    .editGraphics({ target: "yAxisTitle", property: "rotation", value: -Math.PI / 2 })
    .createGraphics({ id: "chartTitle", type: "text" })
    .editGraphics({ target: "chartTitle", property: "x", value: plot.left })
    .editGraphics({ target: "chartTitle", property: "y", value: 18 })
    .editGraphics({ target: "chartTitle", property: "text", value: "Life Expectancy over Time" })
    .editGraphics({ target: "chartTitle", property: "fill", value: "#0f172a" })
    .editGraphics({ target: "chartTitle", property: "fontSize", value: 18 })
    .editGraphics({ target: "chartTitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "chartTitle", property: "fontWeight", value: 700 })
    .editGraphics({ target: "chartTitle", property: "textAlign", value: "left" })
    .editGraphics({ target: "chartTitle", property: "textBaseline", value: "middle" })
    .createGraphics({ id: "chartSubtitle", type: "text" })
    .editGraphics({ target: "chartSubtitle", property: "x", value: plot.left })
    .editGraphics({ target: "chartSubtitle", property: "y", value: 40 })
    .editGraphics({ target: "chartSubtitle", property: "text", value: "UTC year positions · 1955–2005" })
    .editGraphics({ target: "chartSubtitle", property: "fill", value: MUTED })
    .editGraphics({ target: "chartSubtitle", property: "fontSize", value: 12 })
    .editGraphics({ target: "chartSubtitle", property: "fontFamily", value: FONT })
    .editGraphics({ target: "chartSubtitle", property: "fontWeight", value: "normal" })
    .editGraphics({ target: "chartSubtitle", property: "textAlign", value: "left" })
    .editGraphics({ target: "chartSubtitle", property: "textBaseline", value: "middle" });
}
